### ISSUE TITLE
rust cause probleme here?

### ISSUE THREAD

**Issue by ayoubelmhamdi** [robmoss/git-is-my-lab-book#27]
## Probleme

when I try to add `rust` here:
```js
tab_names.set("language-rust", "Rust");
```
https://github.com/robmoss/git-is-my-lab-book/blob/04cb2b05d2a559e8f2ac6c6498b05682697e7bef/tabbed-code-blocks.js#L15

I get this issue, two wiped `Rust` sections
![image](https://user-images.githubusercontent.com/34358145/193376031-038d0385-b810-4eb5-8829-494f88875ec1.png)

## Solution
the solution is to use `Rust` instead of `rust`,
```js
tab_names.set("language-Rust", "Rust");
```

## Question:
could you explain, why I have this bug, and the right way to add a new language without causing this issue again, so my question is: 
- how can get the right name of all languages that are supported by `mdbook`

**Comment by robmoss** [comment]
Hi @ayoubelmhamdi. We haven't used any Rust code blocks in our book, so I hadn't tested this out. It **should** be as simple as adding the following line to `tabbed-code-blocks.js`, just as you did:

```javascript
tab_names.set("language-rust", "Rust");
```

It seems that Rust code blocks use a nested `<pre>` element to contain the action buttons in the top-right corner of the code block, and the current JavaScript code treats `<pre>` element as a separate code block. That's why two tabs appear for a single Rust code block.

I've created pull request #28 which adds support for Rust code blocks and fixes this issue.

Can I ask what you're using tabbed code blocks for?

**Comment by ayoubelmhamdi** [comment]
- why I used tabbed?

I like the idea behind the [rosettacode.org](https://rosettacode.org), it proposes a lot of problems with solutions, using a lot of languages, like `hello-word` that have 536  languages code there,

but already had my algorithms in `c`, so why not, I will try to create a `Rosetta` of theme, using `tabs`

so, I try to create my own [book](https://ayoubelmhamdi.github.io/projects) to accumulate all codes learned by `c`, and I will convert them to other languages that I'm trying to learn `bash`, `python`, and `rust`, in one place nicely,

**Comment by ayoubelmhamdi** [comment]
@robmoss your `PR` is fix, this probleme,thank's so much
